config/routes.rb
FilmProjectRails::Application.routes.draw do

  resources :invitations

  resources :conversations

  resources :messages

  resources :posts do
    resources :comments
  end

  match "/blog/", :to => "posts#index"

  match "/blog/:id", :to => "posts#show"

  get "home/index"
  resources :task_categories

  resources :reminders

  match '/assets', :to => 'assets#index', :via => :get
  match '/assets/upload', :to => 'assets#new', :via => :get
  match '/assets', :to => 'assets#create', :via => :post
  match '/assets/:id', :to => 'assets#show'

  match "/projects", :to => "projects#create", :via => "post"
  match "/projects/menu", :to => "projects#menu"
  match '/projects/index', :to => 'projects#index'
  match '/projects/join', :to => 'projects#join'
  match '/projects/joinaction', :to => 'projects#joinaction', :via => :post
  match '/projects/:id', :to => 'projects#switch' , :via => :post
  resources :projects

  match '/notifications', :to => 'notifications#index'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server, :at => "admin/resque"

  resources :users

  match '/contacts/all', :to => 'users#contacts_all'
  match '/contacts/projects', :to => 'users#contacts_by_project'
  match '/crew', :to => 'users#contacts_by_user_role'

  resources :user_roles

  resources :sessions, :pathnames => { :new => 'signin' }
  resources :signups, :only => [:new, :create], :pathnames => { :new => 'signup'}
  match '/tasks/menu', :to => 'tasks#menu'
  match '/tasks/:id/mark_complete', :to => 'tasks#mark_complete'
  match '/tasks/:id/mark_pending', :to => 'tasks#mark_pending'
  match '/tasks/index_completed', :to => 'tasks#index_completed'
  match '/tasks/all', :to => 'tasks#show_all_tasks_in_project'
  resources :tasks

  match '/signup', :to => 'signups#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signin', :to => 'sessions#new'
  match '/guest', :to => 'sessions#guest'
  match '/invite', :to => 'invitations#invite'

  match '/about', :to => 'home#about'
  match '/comingsoon', :to => 'home#comingsoon'
  match '/changelog', :to => 'changelogs#index'
  match '/auth/:provider/callback', :to => 'sessions#create_facebook'
  match '/auth/failure' => redirect("/")
  match '/oauth2callback', :to => 'sessions#create_google'
  match 'experiments(/:action(/:id))', :to => 'abingo_dashboard', :as => :bingo

        root :to => "home#index"
end

app/models/task_category.rb
class TaskCategory < ActiveRecord::Base
	attr_accessible :name, :created_at, :updated_at, :project_id, :task_category_ids
	has_and_belongs_to_many :tasks
	belongs_to :project
	validates :name, :presence => true
	#validates_numericality_of :project_id

end

app/controllers/task_categories_controller.rb
class TaskCategoriesController < ApplicationController
  # GET /task_categories
  # GET /task_categories.json
  def index
    @task_categories = self.current_project.task_categories.all

    @header = "Task Categories"
    respond_to do |format|
      format.mobile # index.html.erb
      format.json { render json: @task_categories }
    end
  end

  # GET /task_categories/1
  # GET /task_categories/1.json
  def show
    @task_category = TaskCategory.find(params[:id])

    respond_to do |format|
      format.mobile # show.html.erb
      format.json { render json: @task_category }
    end
  end

  # GET /task_categories/new
  # GET /task_categories/new.json
  def new
    @task_category = TaskCategory.new
    respond_to do |format|
      format.mobile # new.html.erb
      format.json { render json: @task_category }
    end
  end

  # GET /task_categories/1/edit
  def edit
    @task_category = TaskCategory.find(params[:id])
  end

  # POST /task_categories
  # POST /task_categories.json
  def create
    @task_category = TaskCategory.new(params[:task_category])
    setDefaults @task_category
    @task_category.save
    respond_to do |format|
        format.mobile { redirect_to task_categories_path, notice: 'Task category was created.' }
    end
  end

  # PUT /task_categories/1
  # PUT /task_categories/1.json
  def update
    @task_category = TaskCategory.find(params[:id])

    respond_to do |format|
      if @task_category.update_attributes(params[:task_category])
        format.mobile { redirect_to task_categories_path, notice: 'Task category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_categories/1
  # DELETE /task_categories/1.json
  def destroy
    @task_category = TaskCategory.find(params[:id])
    @task_category.destroy

    respond_to do |format|
      format.mobile { redirect_to task_categories_path }
      format.json { head :no_content }
    end
  end

  def setDefaults(task_category)

    task_category.project_id = self.current_project.id
  end
end

app/helpers/task_categories_helper.rb
module TaskCategoriesHelper
end

app/views/task_categories/_new_form.html.erb
<%= form_for(@task_category) do |f|  %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_categories/_new_form.mobile.erb
<%= form_for(@task_category, :action => :create) do |f| %>
  <form>
    <ul data-role="listview" data-inset="true">
      <li data-role="fieldcontain">
        <%= f.label :name, "Task Category Name", :"for" => "task-categories-new-form-form-name" %>
        <%= f.text_field :name, :id => "task-categories-new-form-form-name", :placeholder => "Lighting" %>
      </li>
      <li class="ui-body ui-body-b">
        <fieldset class="ui-grid-a">
          <%= f.submit :value => 'Create' %>
        </fieldset>
      </li>
    </ul>
  </form>
<% end %>

app/views/task_categories/edit.html.erb
<h1>Editing task_category</h1>

<%= render 'form' %>

app/views/task_categories/index.html.erb
<h1>Listing task_categories</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @task_categories.each do |task_category| %>
  <tr>
    <td><%= task_category.name %></td>
    <td><%= link_to 'Show', task_category %></td>
    <td><%= link_to 'Edit', edit_task_category_path(task_category) %></td>
    <td><%= link_to 'Destroy', task_category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task category', new_task_category_path, :class => 'btn' %>

app/views/task_categories/index.mobile.erb
<%= link_to "Add a New Category", new_task_category_url, :"data-role" => "button" %>

<br />

<ul data-role="listview">
	<li><%= link_to "All", tasks_path %></li>
	<% @task_categories.each do |task_category| %>
	<li>
		<%= link_to task_category.name, tasks_path( :name => task_category.name) %>
	</li>
	<% end %>
</ul>

app/views/task_categories/new.html.erb
<h1>New task_category</h1>

<%= render 'form' %>

app/views/task_categories/new.mobile.erb
<%= render "new_form" %>

app/views/task_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task_category.name %>
</p>


<%= link_to 'Edit', edit_task_category_path(@task_category) %> |
<%= link_to 'Back', task_categories_path %>