config/routes.rb
FilmProjectRails::Application.routes.draw do

  resources :invitations

  resources :conversations

  resources :messages

  resources :posts do
    resources :comments
  end

  match "/blog/", :to => "posts#index"

  match "/blog/:id", :to => "posts#show"

  get "home/index"
  resources :task_categories

  resources :reminders

  match '/assets', :to => 'assets#index', :via => :get
  match '/assets/upload', :to => 'assets#new', :via => :get
  match '/assets', :to => 'assets#create', :via => :post
  match '/assets/:id', :to => 'assets#show'

  match "/projects", :to => "projects#create", :via => "post"
  match "/projects/menu", :to => "projects#menu"
  match '/projects/index', :to => 'projects#index'
  match '/projects/join', :to => 'projects#join'
  match '/projects/joinaction', :to => 'projects#joinaction', :via => :post
  match '/projects/:id', :to => 'projects#switch' , :via => :post
  resources :projects

  match '/notifications', :to => 'notifications#index'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server, :at => "admin/resque"

  resources :users

  match '/contacts/all', :to => 'users#contacts_all'
  match '/contacts/projects', :to => 'users#contacts_by_project'
  match '/crew', :to => 'users#contacts_by_user_role'

  resources :user_roles

  resources :sessions, :pathnames => { :new => 'signin' }
  resources :signups, :only => [:new, :create], :pathnames => { :new => 'signup'}
  match '/tasks/menu', :to => 'tasks#menu'
  match '/tasks/:id/mark_complete', :to => 'tasks#mark_complete'
  match '/tasks/:id/mark_pending', :to => 'tasks#mark_pending'
  match '/tasks/index_completed', :to => 'tasks#index_completed'
  match '/tasks/all', :to => 'tasks#show_all_tasks_in_project'
  resources :tasks

  match '/signup', :to => 'signups#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signin', :to => 'sessions#new'
  match '/guest', :to => 'sessions#guest'
  match '/invite', :to => 'invitations#invite'

  match '/about', :to => 'home#about'
  match '/comingsoon', :to => 'home#comingsoon'
  match '/changelog', :to => 'changelogs#index'
  match '/auth/:provider/callback', :to => 'sessions#create_facebook'
  match '/auth/failure' => redirect("/")
  match '/oauth2callback', :to => 'sessions#create_google'
  match 'experiments(/:action(/:id))', :to => 'abingo_dashboard', :as => :bingo

        root :to => "home#index"
end

app/models/task.rb
class Task < ActiveRecord::Base
	attr_accessible :name, :time, :description, :created_at, :updated_at, :project_id, :project, :task_status, :task_status_id, :task_priority_id, :task_priority, :task_category_ids, :user_ids, :users

	has_and_belongs_to_many :users
	has_and_belongs_to_many :task_categories
	has_many :notifications, :as => :notification_object, :dependent => :destroy
	belongs_to :project
	belongs_to :task_status
	belongs_to :task_priority
	belongs_to :owner, :class_name => "User", :foreign_key => :owner_id

	validates :name, :presence => true
	validates :task_priority_id, :presence => true
	validates :task_status, :presence => true

	validates :project_id, :presence => true

	def to_s
		self.name
	end

	def formatted_time
		if self.time.nil?
			return "No Start Date"
		else
			return self.time.strftime("%a %b %d %I:%M%p")
		end
	end

	def mark_complete

		if self.task_status != TaskStatus.find_by_name("Complete")
			self.task_status = TaskStatus.find_by_name("Complete")
			self.save
			return true
		else
			return false
		end
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    require 'time'
    def menu

        respond_to do |format|
            format.html
            format.mobile
        end

    end


    def new
        @task = Task.new
        #set the priority to the first priority to make sure there is a default value
        @task.task_priority = TaskPriority.first
        @task_categories = self.current_project.task_categories.find(:all)
        @users = self.current_project.users.all
        @time = Time.now.in_time_zone + 2000
        @title = "Create Task"
        respond_to do |format|
            format.mobile
        end
    end

    def create
        if not is_mobile_device?
            date = Date.strptime(params[:date],"%m-%d-%Y").to_time
            date = date.change(:hour => Time.parse(params[:time2]).hour, :min => Time.parse(params[:time2]).min)
            params[:task][:time] = date
            params[:task][:task_priority] = TaskPriority.find_by_name("Low")
            params[:task][:task_status] = TaskPriority.find_by_name("Pending")
            #make sure they tried to assign it to somebody
            #make sure the task isn't assigned to vagina monsters
            if params[:task][:users] == ["[]"]
                redirect_to tasks_path, :flash => { :notice => "Make sure you assign the task to somebody next time!" }
                return
            end
            @task = Task.new(params[:task])
            setDefaults! @task
        else
            @task = Task.new(params[:task])
            setDefaults! @task
        end

        @task.save

        notification_type = NotificationType.find_or_create_by_name("NewTask")
        notification = nil
        @task.users.each do |user|
            if user != self.current_user
                notification = Notification.create(:notification_type => notification_type, :user => user, :notification_object => @task)
            end
        end
        @title = "Create Task"


        respond_to do |format|
            format.html { redirect_to tasks_url, notice: 'Task Created.' }
            format.mobile { redirect_to tasks_url, notice: 'Task Created.' }
        end
    end

    def edit
        @task = Task.find(params[:id])
        @users = current_project.users.all
        @time = @task.time
        @title = "Edit Task"
        respond_to do |format|
            format.html
            format.mobile
        end
    end

    def update
        params[:task][:task_category_ids] ||= []
        params[:task][:user_ids] ||= []
        @task = Task.find(params[:id])
        @task.update_attributes(params[:task])

        #send a notification to the task owner
        if self.current_user != @task.owner
            Notification.create(:notification_type => NotificationType.find_or_create_by_name("UpdatedTask"), :user => @task.owner, :notification_object => @task)
        end
        #send a notification to all other users on the task
        @task.users.each do |user|
            if user != self.current_user and user != @task.owner
                Notification.create(:notification_type => NotificationType.find_or_create_by_name("UpdatedTask"), :user => user, :notification_object => @task)
            end
        end


        respond_to do |format|
            format.html { redirect_to tasks_url }
            format.mobile { redirect_to @task }
        end
    end

    def mark_complete
        task = Task.find(params[:id])
        if task.mark_complete
            flash[:success] = 'Task marked complete.'
            #send a notification to the task owner
            if self.current_user != task.owner
                Notification.create(:notification_type => NotificationType.find_or_create_by_name("CompletedTask"), :user => task.owner, :notification_object => task)
            end
            #send a notification to all other users on the task
            task.users.each do |user|
                if user != self.current_user and user != task.owner
                    Notification.create(:notification_type => NotificationType.find_or_create_by_name("CompletedTask"), :user => user, :notification_object => task)
                end
            end
        else
            flash[:notice] = 'Task is already marked complete.'
        end
        respond_to do |format|
            format.html { redirect_to tasks_path }
            format.mobile { redirect_to tasks_path}
        end
    end

    def index
        if (params[:mytasks].nil?)
            if(params[:name].nil?)
                @tasks = self.current_project.tasks.find(:all, :conditions => { :task_status_id => TaskStatus.find_by_name("Pending").id})
            else
                @tasks = []
                self.current_project.task_categories.find_by_name(params[:name]).tasks.each do |task|
                    if task.project == self.current_project
                        @tasks << task
                    end
                end
            end
            @tasks = @tasks.sort_by &:time
            @title = "Tasks"
            @header = "All Tasks"
        else
            @tasks = []
            self.current_project.tasks.all.each do |task|
                task.users.each do |user|
                    if user == self.current_user
                        @tasks << task
                    end
                end
            end
            @tasks = @tasks.sort_by &:time
            @title = "My Tasks"
            @header = "My Tasks"
        end

        respond_to do |format|
            format.html
            format.mobile
            format.js
        end

    end

    def index_completed
        if (params[:mytasks].nil?)
            if(params[:name].nil?)
                @tasks = self.current_project.tasks.find(:all, :conditions => { :task_status_id => TaskStatus.find_by_name("Complete").id})
            else
                @tasks = []
                self.current_project.task_categories.find_by_name(params[:name]).tasks.each do |task|
                    if task.project == self.current_project
                        @tasks << task
                    end
                end
            end
            @title = "Completed Tasks"
            @header = "All Tasks"
        else
            @tasks = []
            self.current_project.tasks.all.each do |task|
                task.users.each do |user|
                    if user == self.current_user
                        @tasks << task
                    end
                end
            end
            @title = "Completed Tasks"
            @header = "My Tasks"
        end

        respond_to do |format|
            format.html
            format.mobile
            format.js
        end

    end

    def show_all_tasks_in_project
        @tasks = self.current_project.tasks.all

        respond_to do |format|
            format.html
            format.mobile
            format.js
        end
    end

    def show
        @task = self.current_project.tasks.find_by_id(params[:id])
        @title = "Task"
        if @task.nil?
            flash[:success] =  'Task not found. Maybe it is on a different project'
            respond_to do |format|
                format.html { redirect_to tasks_path }
                format.mobile { redirect_to tasks_path }
            end
        else
            respond_to do |format|
                format.html
                format.mobile
            end
        end
    end

    def destroy
        task = self.current_project.tasks.find_by_id(params[:id])
        task.destroy

        respond_to do |format|
            format.html { redirect_to tasks_url, notice: 'Task Deleted.' }
            format.mobile { redirect_to tasks_url, notice: 'Task Deleted.' }
        end
    end

    def setDefaults!(task)
        task.task_status = TaskStatus.first
        task.owner ||= self.current_user
        task.project_id ||= self.current_project.id
        task.task_status = TaskStatus.find_by_name("Pending")
        task.active = true
    end
end

app/helpers/tasks_helper.rb
module TasksHelper

	def mark_task_complete_path(id)
		"/tasks/" + id.to_s + "/mark_complete"
	end

	def mark_task_pending_path(id)
		"/tasks/" + id.to_s + "/mark_pending"
	end
end

app/views/tasks/_add_user_modal.html.erb
<div class="modal" id="tasks-new-add-user-modal">
	<div class="modal-header">
		<button class="close" data-dismiss="modal">×</button>
		<h3>Choose User</h3>
	</div>
	<div id="tasks-new-add-user-modal-radio-buttons">
		<% self.current_project.users.each do |contact| %>
			<input type="checkbox" name="contacts-group" value="<%= contact.id %>" <% if @task.users.include?(contact) %> checked = 'checked' <% end %>><text><%= contact.name %></text><br>
		<% end %>
	</div>
	<button id="tasks-new-add-user-modal-select-button" class="btn">Select User</button>
</div>

app/views/tasks/_form.html.erb
<%= render "add_user_modal" %>
<%= form_for(@task) do |f| %>
    <% if @task.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

            <ul>
                <% @task.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
    </div>
    <%= label_tag :user_name, "Assign To" %>
    <% if @task.users.count != 0%>
        <% @task.users.each do |user| %>
                <%= f.hidden_field :user, :class => "tasks-new-user-id", :value => "#{user.id}", :name => "task[users][]" %>
                <% if user == @task.users.last %>
                    <%= text_field_tag :users_name, nil, :class => "tasks-new-user-name", :disabled => true, :value => "#{user.name}", :style => "display: inline;"  %>
                <% else %>
                    <%= text_field_tag :users_name, nil, :class => "tasks-new-user-name", :disabled => true, :value => "#{user.name}" %>
                <% end %>
        <% end %>
    <% else %>
        <%= f.hidden_field :users, :class => "tasks-new-user-id", :name => "task[users][]" %>
        <%= text_field_tag :user_name, nil, :class => "tasks-new-user-name", :disabled => true, :style => "display: inline;" %>
    <% end %>
    <button class="btn" id="tasks-new-add-user-button" type="button">
        <i class="icon-plus icon-white"></i>
    </button>


    <div class="field">
        <%= f.label :date, "Date" %><br />
        <div class="input-append date" id="tasks-tasks-new" data-date="<%= @time.strftime("%m-%d-%Y") %>" data-date-format="mm-dd-yyyy">
            <%= text_field_tag(:date, @time.strftime("%m-%d-%Y"), :class => "span2", :size => "16", :readonly => true) %>
            <span class="add-on">
                <i class="icon-th"></i>
            </span>
        </div>
        <br>
        <%= label_tag :time2, "Time" %>
        <%= text_field_tag :time2, nil, :type => "time", :id => "tasks-tasks-time", :text => "test" %>
    </div>
    <div class="field">
        <%= f.label :description %><br />
        <%= f.text_area :description, :id => "tasks-form-description" %>
    </div>
    <div class="actions">
        <%= f.submit :class => "btn" %>
    </div>
<% end %>

app/views/tasks/_form.mobile.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <!-- ///////////////////////////////////////////////////////////////////////////////////////// -->
<!--  

-->  

  
  <form>
		<ul data-role="listview" data-inset="true">
	   <!-- TASK NAME -->
			<li data-role="fieldcontain">
				<label for="task-new-taskname"><%= 'Task Name:' %></label>
				<%= f.text_field :name, :id => "task-new-taskname", :placeholder => "Task Name" %>
					<!-- HTML <input type="text" name="task-new-taskname" id="task-new-taskname"/> -->
			</li>
       <!-- DESCRIPTION -->
			<li data-role="fieldcontain">
				<label for="task-new-taskdescription"><%= 'Description:' %></label>
				<%= f.text_area :notes, :id => "task-new-taskdescription" %>
				
					<!-- HTML <textarea cols="40" rows="8" name="task-new-taskdescription" id="task-new-taskdescription"></textarea> -->
			</li>
		<!-- PRIOTITY -->
			<li data-role="fieldcontain">
				<fieldset data-role="controlgroup" data-type="horizontal">
			     	<legend>Priority:</legend>
			         	<input type="radio" name="task-new-priority" id="task-new-priority-low" value="0" />
						<label for="task-new-priority-low"><%= 'Low' %></label>
			         	<input type="radio" name="task-new-priority" id="task-new-priority-medium" value="medium" checked="checked" />
			         	<label for="task-new-priority-medium"><%= 'Medium' %></label>
			         	<input type="radio" name="task-new-priority" id="task-new-priority-high" value="High" />
			         	<label for="task-new-priority-high"><%= 'High' %></label>			
			    </fieldset>
				<%= f.number_field :priority %>
			</li>
			
		<!-- START DATE -->
			<li data-role="fieldcontain">
				<label for="task-new-startdate"><%= 'Start Date' %></label>
				<input name="task-new-startdate" id="task-new-startdate" type="date" data-role="datebox"
   			data-options='{"mode": "calbox", "calTodayButton": true}'>
			<%= f.datetime_select :startdate, :type => "date", "data-role" => "datebox" %>
			
					
			</li>	
			
		<!-- END DATE -->
   		<li data-role="fieldcontain">
					<label for="task-new-enddate"><%= 'End Date' %></label>
					<input name="task-new-enddate" id="task-new-enddate" type="date" data-role="datebox"
   				data-options='{"mode": "calbox", "calTodayButton": true}'>
			<%= f.datetime_select :enddate %>
   		</li>
			
			  
				
 
  


		
	<!-- CREATE-->
			<li class="ui-body ui-body-b">
				<fieldset class="ui-grid-a">
						<%= f.submit :value => 'Create' %>
						<!-- <button type="submit" data-theme="a">Create</button> -->
			    </fieldset>
			</li>
			
		</ul>
		
		</form>

  <!-- ///////////////////////////////////////////////////////////////////////////////////////// -->


 



<% end %>

app/views/tasks/_index.html.erb
<h1>Listing tasks</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Time</th>
    <th>Description</th>
    <th>Priority</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.formatted_time %></td>
    <td><%= task.description %></td>
    <td><%= task.task_priority.name %></td>
    <td><%= task.task_status.name %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

app/views/tasks/edit.mobile.erb
<%= render 'edit_form' %>

app/views/tasks/index.html.erb
<h1>Your Tasks</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Due</th>
    <th>Description</th>
    <th>Priority</th>
    <th>Status</th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to task.name, task_path(task) %></td>
    <td><%= task.formatted_time %></td>
    <td><%= task.description %></td>
    <td><%= task.task_priority.name %></td>
    <td><%= task.task_status.name %></td>
    <% if self.current_project.administrators.include?(self.current_user) %>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path, :class => "btn" %>
<%= link_to 'View Completed Tasks', '/tasks/index_completed', :class => "btn" %>
<%= link_to "View Entire Project\'s Tasks", '/tasks/all', :class => "btn" %>

app/views/tasks/index_completed.html.erb
<h1>Completed tasks</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Time</th>
    <th>Description</th>
    <th>Priority</th>
    <th>Status</th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.name.split(' ').map {|w| w.capitalize }.join(' ') %></td>
    <td><%= task.formatted_time %></td>
    <td><%= task.description %></td>
    <td><%= task.task_priority.name %></td>
    <td><%= task.task_status.name %></td>
    <td><%= link_to 'Show', task %></td>
    <% if self.current_project.administrators.include?(self.current_user) %>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/index_completed.mobile.erb
<h1>Completed Tasks</h1>

<ul data-role="listview" data-inset="true">
<% @tasks.each do |task| %>
    <% if task.active %>
       <li><a href= "<%= "/tasks/#{task.id}" %>">

                    <h3><%= task.name.split(' ').map {|w| w.capitalize }.join(' ') %></h3>
                    <p>Status: <%= task.task_status.name %></p>
                    <p>Priority: <%= task.task_priority.name %></p>
                    <p><%= task.formatted_time %></p>

                </a></li>
    <% end %>
<% end %>
</ul>

app/views/tasks/menu.mobile.erb
<ul data-role="listview">
	<li>
      <%= link_to "Create a Task", new_task_path %>
    </li>
    <li>
      <%= link_to "View My Tasks", tasks_path(:mytasks => 1) %>
    </li>
	<li>
      <%= link_to "View All Tasks", tasks_path %>
    </li>
    <li>
      <%= link_to "View Tasks by Categories", task_categories_path %>
    </li>
    <li>
    	<%= link_to "Add a New Category", new_task_category_url %>
    </li>
</ul>

app/views/tasks/new.mobile.erb
<!--#<h1>New task</h1> -->

<%= render 'new_form' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<div>
  <p>
    <h1><%= @task.name.split(' ').map {|w| w.capitalize }.join(' ') %></h1>
  </p>
  <p>
    <b>Owner:</b>
    <%= @task.owner %>
  </p>
  <p>
    <b>Due:</b>
    <%= @task.formatted_time %>
  </p>

  <p>
    <b>Description:</b>
    <%= @task.description %>
  </p>

  <p>
    <b>Priority:</b>
    <%= @task.task_priority %>
  </p>

  <p>
    <b>Status:</b>
    <%= @task.task_status %>
  </p>

  <p>
    <b>Participants:</b>
    <ul>
      <% @task.users.all.each do |user| %>
      <% if @task.owner != user %>
      <li> <%= user.name.split(' ').map {|w| w.capitalize }.join(' ') %> </li>

      <% end %>
      <% end %>
    </ul>
  </p>

  <%= link_to 'Mark Complete', mark_task_complete_path(@task.id), :class => "btn btn-primary"%>

  <% if self.current_project.administrators.include?(self.current_user) %>
  <%= link_to 'Edit', edit_task_path(@task), :class => "btn" %>
  <% end %>
</div>

app/views/tasks/show_all_tasks_in_project.html.erb
<h1>All Tasks</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Due</th>
    <th>Description</th>
    <th>Priority</th>
    <th>Status</th>
    <th>Owner</th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= link_to task.name, task_path(task) %></td>
    <td><%= task.formatted_time %></td>
    <td><%= task.description %></td>
    <td><%= task.task_priority.name %></td>
    <td><%= task.task_status.name %></td>
    <td><%= task.owner %></td>
    <% if self.current_project.administrators.include?(self.current_user) %>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path, :class => "btn" %>
<%= link_to 'View Completed Tasks', '/tasks/index_completed', :class => "btn" %>
<%= link_to "View Entire Project\'s Tasks", '/tasks/all', :class => "btn" %>