config/routes.rb
FilmProjectRails::Application.routes.draw do

  resources :invitations

  resources :conversations

  resources :messages

  resources :posts do
    resources :comments
  end

  match "/blog/", :to => "posts#index"

  match "/blog/:id", :to => "posts#show"

  get "home/index"
  resources :task_categories

  resources :reminders

  match '/assets', :to => 'assets#index', :via => :get
  match '/assets/upload', :to => 'assets#new', :via => :get
  match '/assets', :to => 'assets#create', :via => :post
  match '/assets/:id', :to => 'assets#show'

  match "/projects", :to => "projects#create", :via => "post"
  match "/projects/menu", :to => "projects#menu"
  match '/projects/index', :to => 'projects#index'
  match '/projects/join', :to => 'projects#join'
  match '/projects/joinaction', :to => 'projects#joinaction', :via => :post
  match '/projects/:id', :to => 'projects#switch' , :via => :post
  resources :projects

  match '/notifications', :to => 'notifications#index'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  mount Resque::Server, :at => "admin/resque"

  resources :users

  match '/contacts/all', :to => 'users#contacts_all'
  match '/contacts/projects', :to => 'users#contacts_by_project'
  match '/crew', :to => 'users#contacts_by_user_role'

  resources :user_roles

  resources :sessions, :pathnames => { :new => 'signin' }
  resources :signups, :only => [:new, :create], :pathnames => { :new => 'signup'}
  match '/tasks/menu', :to => 'tasks#menu'
  match '/tasks/:id/mark_complete', :to => 'tasks#mark_complete'
  match '/tasks/:id/mark_pending', :to => 'tasks#mark_pending'
  match '/tasks/index_completed', :to => 'tasks#index_completed'
  match '/tasks/all', :to => 'tasks#show_all_tasks_in_project'
  resources :tasks

  match '/signup', :to => 'signups#new'
  match '/signout', :to => 'sessions#destroy'
  match '/signin', :to => 'sessions#new'
  match '/guest', :to => 'sessions#guest'
  match '/invite', :to => 'invitations#invite'

  match '/about', :to => 'home#about'
  match '/comingsoon', :to => 'home#comingsoon'
  match '/changelog', :to => 'changelogs#index'
  match '/auth/:provider/callback', :to => 'sessions#create_facebook'
  match '/auth/failure' => redirect("/")
  match '/oauth2callback', :to => 'sessions#create_google'
  match 'experiments(/:action(/:id))', :to => 'abingo_dashboard', :as => :bingo

        root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
   @signup = Signup.new
   if self.current_user? && !is_mobile_device?
    index_signed_in
    render :action => :index_signed_in
    return
  end
  respond_to do |format|
    format.html
      #format.mobile
    end
  end

  def index_signed_in
    if self.current_project.nil?
      @no_project = true
    else
      if self.current_project.users.count == 1
        @empty_project = true
      else
        if self.current_project.tasks.count == 0
          @no_tasks = true
        end
      end
    end
  end

  def comingsoon
  	respond_to do |format|
  		format.html
  		format.mobile
  	end
  end

  def about
  end
end

# private
#
#  def is_mobile
#      request.format = :mobile if is_mobile_device?
#   end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>Our Story</h1>
<p>Through extensive market research and interviews with industry players, such as production managers, executive assistants at studios, production firms, and finance professionals, we discovered a valuable opportunity to improve the production process through enhanced communication and coordination tools. We found that the current process is grounded in archaic processes that result in numerous on (and off) set inefficiencies. Our team assembled though a combination of luck, fate, and love for collecting circa 1830's Elgin pocket watches.</p>
<h1>The Crew</h1>
<!-- Gabriel Brotman !-->
<div class="row home-about-rowclass">
  <div class="span3">
    <%= image_tag "bio/brotman.jpg", :height => 150, :width => 150 %>
  </div>
  <div class="span9 home-about-blockquote" >
    <blockquote>
      <p>Gabe is a fourth-year Communication Studies and American Studies student at Northwestern University. Despite a lifelong battle with coding illiteracy, he is passionate about developing and launching great products that make people’s day a little easier. Gabe's an avid news junkie, and has worked in business development, research, and sales and marketing at several media and communications companies.</p>
      <small>Gabriel Brotman</small>
    </blockquote>
  </div>
</div>

<!-- Taylor Culbertson !-->
<div class="row home-about-rowclass">
  <div class="span3">
    <%= image_tag "bio/taylor.jpg", :height => 150, :width => 150 %>
  </div>
  <div class="span9 home-about-blockquote" >
    <blockquote>
      <p>Taylor is loose cannon programmer, director and VFX artist who is out to revolutionize the way visual media is consumed by the masses.  From Pittsburgh, he’s worked heavily in both entrepreneurial start-ups and film; helping to develop “Synthetic Interview” technology at GetAbby, creating interactive children’s applications that teach programming skills at Northwestern, and directing a 60-person crew in <i>Cadence</i>, which strove weave modern VFX within a classic Greek narrative.</p>
      <small>Taylor Culbertson</small>
    </blockquote>
  </div>
</div>

<!-- Chris Erwin !-->
<div class="row home-about-rowclass">
  <div class="span3">
    <%= image_tag "bio/chris.jpg", :height => 150, :width => 150 %>
  </div>
  <div class="span9 home-about-blockquote" >
    <blockquote>
      <p>Chris likes tech startups. He also likes product management, business development and marketing strategy. A former banker from New York City, Chris eventually saw the entrepreneurial light and came over to the other side. He’s also trying to learn Python and asks his team members way too many questions about recursive programming. A graduate of Tufts University, Chris is now hoping to finish up at the Kellogg School of Management in June (fingers crossed).</p>
      <small>Chris Erwin</small>
    </blockquote>
  </div>
</div>

<!-- Jonathan Friedman !-->
<div class="row home-about-rowclass">
  <div class="span3">
    <%= image_tag "bio/jonathan.jpg", :height => 150, :width => 150 %>
  </div>
  <div class="span9 home-about-blockquote" >
    <blockquote>
      <p>Jon is an entrepreneur and programmer with one successful business under his belt. His passion for tinkering has led to several websites, applications and even free laundry. Given the choice, Jon would pick soup over salad, Vim over Emacs, Xbox over Playstation, and sun over snow. With luck, he will finish a joint BA/MS degree in computer science around June 2013.</p>
      <small>Jonathan Friedman</small>
    </blockquote>
  </div>
</div>

<!-- Scottie Gambill !-->
<div class="row home-about-rowclass">
  <div class="span3">
    <%= image_tag "bio/scottie.jpg", :height => 150, :width => 150 %>
  </div>
  <div class="span9 home-about-blockquote" >
    <blockquote>
      <p>Scottie is the token female on the team. She has a Computer Engineering degree that has been on a shelf while she has worked in finance, product management and innovation consulting over the past five years. In her free time she loves photography, traveling, and creating kick-ass film production management software. She is currently wrapping up receiving her MBA from the Kellogg School of Management. </p>
      <small>Scottie Gambill</small>
    </blockquote>
  </div>
</div>

<!-- Kashif Malik !-->
<div class="row home-about-rowclass">
  <div class="span3">
    <%= image_tag "bio/kashif.jpg", :height => 150, :width => 150 %>
  </div>
  <div class="span9 home-about-blockquote" >
    <blockquote>
      <p>Kashif is officially an Electrical Engineer, but his passion lies in so many areas besides that. He runs a VFX studio that specializes in all things film, whilst also working at a robotics lab dealing with mechatronics. He loves steak and long walks on the beach. His biggest passion perhaps is being his own boss, which puts him in a great position working on this startup with the team.</p>
      <small>Kashif Malik</small>
    </blockquote>
  </div>
</div>

<!-- Ryan McAfee !-->
<div class="row home-about-rowclass">
  <div class="span3">
    <%= image_tag "bio/ryan.jpg", :height => 150, :width => 150 %>
  </div>
  <div class="span9 home-about-blockquote" >
    <blockquote>
      <p>Ryan has long been obsessed with entrepreneurship. He is a sophomore computer science undergraduate at Northwestern University, and hopes this new opportunity will give him a good reason to drop out and champion the start-up path instead (he acknowledges that successful business-people who drop out of college are way more bad-ass and get all the ladies).</p>
      <small>Ryan McAfee</small>
    </blockquote>
  </div>
</div>

<!-- Gabriel Peal !-->
<div class="row home-about-rowclass">
  <div class="span3">
    <%= image_tag "bio/gabe.jpg", :height => 150, :width => 150 %>
  </div>
  <div class="span9 home-about-blockquote" >
    <blockquote>
      <p>Gabriel Peal is an Electrical Engineering student at Northwestern University. He has a passion for consumer technology and is a firm believer that you can't over estimate the importance of user experience. He has worked as a software developer for General Motors, XFI Corporation, and the National Institutes of Health. He has lived in San Francisco and Washington DC, but currently lives in Chicago. </p>
      <small>Gabriel Peal</small>
    </blockquote>
  </div>
</div>

app/views/home/comingsoon.html.erb
 <h1 class="center-text">We're Still Working On This One!</h1>
 <h3 class="center-text">We'll Let You Know When It's Ready</h3>
 <%= image_tag "mobile/home/comingsoon_small.png", :class => "center-image" %>

app/views/home/comingsoon.mobile.erb
 <h1 class="center-text">We're Still Working On This One!</h1>
 <h3 class="center-text">We'll Let You Know When It's Ready</h3>
 <%= image_tag "mobile/home/comingsoon_small.png", :class => "center-image" %>

app/views/home/index.html.erb
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit" id="home-index-hero">
  <div class="row">
    <div class="span3" id="home">
      <%= image_tag "home/hand.png", "id" => "home-index-handjpg" %>
    </div>
    <div class="span5 offset2" id="home-index-list">
      <ul class="unstyled">
        <li><h1>Lights.</h1></li>
        <li><h1>Camera.</h1></li>
        <li><h1>Stagecoach.</h1></li>
      </ul>
      <p id="home-index-paragraph">
        <h2>Stagecoach makes video production easier, faster, and more cost effective for film, TV, and commercial advertising professionals</h2>
      </p>
    </div>

    <div class="row" id="features">
      &nbsp;
    </div>
    <span >
    </span>
    <div class="row">
     <div class="span11">
      <p>
        <h2>
          Introducing you to the only ubiquitous crew sourcing and team management platform that follows the entire lifecycle of your production.
        </h2>
      </p>
    </div>
    <div class="row span12" id="home-index-mockuptitle-row">
      <div class="span4 home-index-mockuptitle" id="home-index-mockuptitle-left">
        <h3>
          Crew Sourcing
        </h3>
      </div>
      <div class="span3 home-index-mockuptitle"  id="home-index-mockuptitle-center">
        <h3>
          Project Management
        </h3>
      </div>
      <div class="span4 home-index-mockuptitle" id="home-index-mockuptitle-right">
        <h3>
          Digital Archiving
        </h3>
      </div>
      <div class="row span12" style="margin-left: 59px;">
        <div class="row span12">
          <%= image_tag "home/sourcing.jpg", "class" => "thumbnail span3 home-index-featureimg" %>
          <%= image_tag "home/mobile.png", "class" => "thumbnail span3" %>
          <%= image_tag "home/tasks.jpg", "class" => "thumbnail span3 home-index-featureimg" %>
          <div class="row span12">
            <p class="span3" id="home-index-mockupdescription-left">
              Assemble a crew by easily accessing digitally stored contact information from all past projects!
            </p>
            <p class="span3" id="home-index-mockupdescription-center">
              Quickly and easily assign tasks and deadlines to crew members and track completion both at the office and on the go!
            </p>
            <p class="span3" id="home-index-mockupdescription-right">
              Effortlessly store and categorize project resources like contact lists and preferred locations!
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="row" id="signup">
      &nbsp;
    </div>
    <div class="row span8">
     <h2>Like what you see? Sign up to be an alpha tester!</h2>
     <br><br>
     <div class="row well span8 offset1">
      <h3 class="offset2">We will email you when we're ready!</h3>
      <%= render 'signups/signup-form' %>
    </div >
  </div>

  <div class="row" id="about">
    &nbsp;
  </div>
  <div class="span11">
    <h1>Our Story</h1>
    <br>
    <p>Through extensive market research and interviews with industry players, such as production managers, executive assistants at studios, production firms, and finance professionals, we discovered a valuable opportunity to improve the production process through enhanced communication and coordination tools. We found that the current process is grounded in archaic processes that result in numerous on (and off) set inefficiencies. Our team assembled though a combination of luck, fate, and love for collecting circa 1830's Elgin pocket watches.</p>
    <br>
    <br>
    <h1>The Crew</h1>
    <!-- Gabriel Brotman !-->
    <div class="row home-about-rowclass">
      <div class="span2">
        <%= image_tag "bio/brotman.jpg", :height => 150, :width => 150 %>
      </div>
      <div class="span9 home-about-blockquote" >
        <blockquote>
          <p>Gabe is a fourth-year Communication Studies and American Studies student at Northwestern University. Despite a lifelong battle with coding illiteracy, he is passionate about developing and launching great products that make people’s day a little easier. Gabe's an avid news junkie, and has worked in business development, research, and sales and marketing at several media and communications companies.</p>
          <small>Gabriel Brotman</small>
        </blockquote>
      </div>
    </div>

    <!-- Taylor Culbertson !-->
    <div class="row home-about-rowclass">
      <div class="span2">
        <%= image_tag "bio/taylor.jpg", :height => 150, :width => 150 %>
      </div>
      <div class="span9 home-about-blockquote" >
        <blockquote>
          <p>Taylor is loose cannon programmer, director and VFX artist who is out to revolutionize the way visual media is consumed by the masses.  From Pittsburgh, he’s worked heavily in both entrepreneurial start-ups and film; helping to develop “Synthetic Interview” technology at GetAbby, creating interactive children’s applications that teach programming skills at Northwestern, and directing a 60-person crew in <i>Cadence</i>, which strove weave modern VFX within a classic Greek narrative.</p>
          <small>Taylor Culbertson</small>
        </blockquote>
      </div>
    </div>

    <!-- Chris Erwin !-->
    <div class="row home-about-rowclass">
      <div class="span2">
        <%= image_tag "bio/chris.jpg", :height => 150, :width => 150 %>
      </div>
      <div class="span9 home-about-blockquote" >
        <blockquote>
          <p>Chris likes tech startups. He also likes product management, business development and marketing strategy. A former banker from New York City, Chris eventually saw the entrepreneurial light and came over to the other side. He’s also trying to learn Python and asks his team members way too many questions about recursive programming. A graduate of Tufts University, Chris is now hoping to finish up at the Kellogg School of Management in June (fingers crossed).</p>
          <small>Chris Erwin</small>
        </blockquote>
      </div>
    </div>

    <!-- Jonathan Friedman !-->
    <div class="row home-about-rowclass">
      <div class="span2">
        <%= image_tag "bio/jonathan.jpg", :height => 150, :width => 150 %>
      </div>
      <div class="span9 home-about-blockquote" >
        <blockquote>
          <p>Jon is an entrepreneur and programmer with one successful business under his belt. His passion for tinkering has led to several websites, applications and even free laundry. Given the choice, Jon would pick soup over salad, Vim over Emacs, Xbox over Playstation, and sun over snow. With luck, he will finish a joint BA/MS degree in computer science around June 2013.</p>
          <small>Jonathan Friedman</small>
        </blockquote>
      </div>
    </div>

    <!-- Scottie Gambill !-->
    <div class="row home-about-rowclass">
      <div class="span2">
        <%= image_tag "bio/scottie.jpg", :height => 150, :width => 150 %>
      </div>
      <div class="span9 home-about-blockquote" >
        <blockquote>
          <p>Scottie is the token female on the team. She has a Computer Engineering degree that has been on a shelf while she has worked in finance, product management and innovation consulting over the past five years. In her free time she loves photography, traveling, and creating kick-ass film production management software. She is currently wrapping up receiving her MBA from the Kellogg School of Management. </p>
          <small>Scottie Gambill</small>
        </blockquote>
      </div>
    </div>

    <!-- Kashif Malik !-->
    <div class="row home-about-rowclass">
      <div class="span2">
        <%= image_tag "bio/kashif.jpg", :height => 150, :width => 150 %>
      </div>
      <div class="span9 home-about-blockquote" >
        <blockquote>
          <p>Kashif is officially an Electrical Engineer, but his passion lies in so many areas besides that. He runs a VFX studio that specializes in all things film, whilst also working at a robotics lab dealing with mechatronics. He loves steak and long walks on the beach. His biggest passion perhaps is being his own boss, which puts him in a great position working on this startup with the team.</p>
          <small>Kashif Malik</small>
        </blockquote>
      </div>
    </div>

    <!-- Ryan McAfee !-->
    <div class="row home-about-rowclass">
      <div class="span2">
        <%= image_tag "bio/ryan.jpg", :height => 150, :width => 150 %>
      </div>
      <div class="span9 home-about-blockquote" >
        <blockquote>
          <p>Ryan has long been obsessed with entrepreneurship. He is a sophomore computer science undergraduate at Northwestern University, and hopes this new opportunity will give him a good reason to drop out and champion the start-up path instead (he acknowledges that successful business-people who drop out of college are way more bad-ass and get all the ladies).</p>
          <small>Ryan McAfee</small>
        </blockquote>
      </div>
    </div>

    <!-- Gabriel Peal !-->
    <div class="row home-about-rowclass">
      <div class="span2">
        <%= image_tag "bio/gabe.jpg", :height => 150, :width => 150 %>
      </div>
      <div class="span9 home-about-blockquote" >
        <blockquote>
          <p>Gabriel Peal is an Electrical Engineering student at Northwestern University. He has a passion for consumer technology and is a firm believer that you can't over estimate the importance of user experience. He has worked as a software developer for General Motors, XFI Corporation, and the National Institutes of Health. He has lived in San Francisco and Washington DC, but currently lives in Chicago. </p>
          <small>Gabriel Peal</small>
        </blockquote>
      </div>
    </div>
  </div>

</div>

app/views/home/index.mobile.erb
<fieldset class="menu-grid-row container_12">
    <div class="grid_4">
        <%= link_to image_tag("mobile/home/tasks_small.png", :class => "menu-grid-icon"), task_menu_path %>
        <div class="menu-grid-icon-text">
            Tasks
        </div>
    </div>
    <div class="grid_4">
        <%= link_to image_tag("mobile/home/assets_small.png", :class => "menu-grid-icon"), assets_path %>
        <div class="menu-grid-icon-text">
            Assets
        </div>
    </div>
    <div class="grid_4">
        <%= link_to image_tag("mobile/home/schedule_small.png", :class => "menu-grid-icon"), comingsoon_path %>
        <div class="menu-grid-icon-text">
            Schedule
        </div>
    </div>
</fieldset>
<fieldset class="container_12 menu-grid-row">
    <div class="grid_4">
        <%= link_to image_tag("mobile/home/contacts_small.png", :class => "menu-grid-icon"), users_path %>
        <div class="menu-grid-icon-text">
            Contacts
        </div>
    </div>
    <div class="grid_4">
        <%= link_to image_tag("mobile/home/profile_small.png", :class => "menu-grid-icon"), self.current_user %>
        <div class="menu-grid-icon-text">
            Profile
        </div>
    </div>
    <div class="grid_4">
        <%= link_to image_tag("mobile/home/projects_small.png", :class => "menu-grid-icon"), project_menu_path %>
        <div class="menu-grid-icon-text">
            Projects
        </div>
    </div>
</fieldset>
<fieldset class="container_12">
    <div class="grid_4">
        <%= link_to image_tag("mobile/home/settings_small.png", :class => "menu-grid-icon"), comingsoon_path %>
        <div class="menu-grid-icon-text">
            Settings
        </div>
    </div>
    <div class="grid_4">
        <%= link_to image_tag("mobile/home/notifications_small.png", :class => "menu-grid-icon"), notifications_path %>
        <div class="menu-grid-icon-text">
            Notifications
        </div>
    </div>
</fieldset>

app/views/home/index_signed_in.html.erb
<h2>Welcome <%= self.current_user.name %></h2>
<br>
<% if @no_project %>
	<p> THE HORROR! You are not currently in a project! Choose one of the options below and hope everything works out for the best:</p>

	<p><%= link_to "Create a Project".html_safe, url_for(:controller => :projects, :action => :new), :class => "btn btn-primary btn-large"%>

	<%= link_to "Join a Project".html_safe, url_for(:controller => :projects, :action => :join), :class => "btn btn-secondary btn-large"%></p>
<% else %>
	<% if @empty_project %>
		<p>Your project has no one in it! Start building your team by inviting people. Sound off like you got a pair!</p>
		<%= link_to "Invite People".html_safe, url_for(:controller => :invitations, :action => :new), :class => "btn btn-primary btn-large"%>
	<% else %>
		<% if @no_tasks %>
			<p>Looks like you have no tasks! Create some tasks and assign them to people.<p>
				<%= link_to "Create Tasks".html_safe, url_for(:controller => :tasks, :action => :new), :class => "btn btn-primary btn-large"%>
		<% else %>
			<p><%= self.current_project.capitalized_name %> has been set up. Enjoy using Stagecoach and feel free to leave us some feedback by emailing us <a href="mailto:chris@projectstagecaoch.com">here</a>!</p>
		<% end %>
	<% end %>
<% end %>